export const SET_APP_ERROR = 'SET_APP_ERROR';
export const SET_LOGIN_ERROR = 'SET_LOGIN_ERROR';
export const SET_APP_LOADING = 'SET_APP_LOADING';
export const SET_APP_LOADING_MESSAGE = 'SET_APP_LOADING_MESSAGE';
export const SET_APP_READY = 'SET_APP_READY';
export const REPLACE_APP_STATE = 'REPLACE_APP_STATE';
export const SET_THEME = 'SET_THEME';

export const APP_ACTIONS = {
  SET_APP_ERROR,
  SET_APP_LOADING,
  SET_APP_LOADING_MESSAGE,
  SET_APP_READY,
  SET_THEME,
  SET_LOGIN_ERROR
};
